# =============================================================================
# C O P Y R I G H T
# -----------------------------------------------------------------------------
# Copyright (c) 2021-2022 by Helmut Konrad Fahrendholz. All rights reserved.
# This file is property of Helmut Konrad Fahrendholz. Any unauthorized copy,
# use or distribution is an offensive act against international law and may
# be prosecuted under federal law. Its content is company confidential.
# =============================================================================

import utila

ABBREVIATION = utila.splitlines("""
ABBREVIATION
ABBREVIATIONS
ABBREVIATIONTABLE
ABKÜRZUNGEN
ABKÜRZUNGEN UND SYMBOLE
ABKÜRZUNGSVERZEICHNIS
ACRONYME
ACRONYMS
LIST OF ABBREVIATIONS
""")

ABSTRACT = utila.splitlines("""
ABSTRACT
ABSTRACT IN ENGLISH
ABSTRACT OF THE DISSERTATION
ABSTRACT OF THE THESIS
ABSTRAKT AUF DEUTSCH
AN ABSTRACT OF THE THESIS OF
EXECUTIVE SUMMARY
KURZFASSUNG
KURZZUSAMMENFASSUNG
ZUSAMMENFASSUNG
""")

ACKNOWLEDGE = utila.splitlines("""
ACKNOWLEDGE
ACKNOWLEDGEMENT
ACKNOWLEDGEMENTS
ACKNOWLEDGMENT
ACKNOWLEDGMENTS
DANKSAGUNG
DANKSAGUNGEN/WIDMUNGEN
DEDICATION
""")

APPENDIX = utila.splitlines("""
ANHANG
ANHANGSVERZEICHNIS
APPENDICES
APPENDIX
EDITION
NOMENCLATURE
A. ANHANG
B. ANHANG
C. ANHANG
D. ANHANG
ANHANG 1
ANHANG 2
ANHANG 3
ANHANG 4
ANHANG 5
ANHANG 6
ANHANG 7
ANHANG 8
ANHANG 9
ANHANG 10
ANHANG A
ANHANG B
ANHANG C
ANHANG D
I ANHANG
II ANHANG
III ANHANG
IIII ANHANG
IV ANHANG
V ANHANG
VI ANHANG
VII ANHANG
VIII ANHANG
VERZEICHNISSE
VORBEMERKUNG ZUR EDITION
""")

BIBLIOGRAPHY = utila.splitlines("""
AUFSÄTZE
AUFSÄTZE AUS SAMMELWERKEN/HERAUSGEBERSCHRIFTEN
AUFSÄTZE AUS ZEITSCHRIFTEN
BIBLIOGRAFIE
BIBLIOGRAPHIE
BIBLIOGRAPHY
HAUPTLITERATUR
INTERNETLITERATUR
INTERNETQUELLEN
LITERATUR
LITERATUR UND QUELLENVERZEICHNIS
LITERATUR- UND QUELLENVERZEICHNIS
LITERATURANGABEN
LITERATURE
LITERATURLISTE
LITERATURVERZEICHNIS
MONOGRAFIEN
PERSONENREGISTER
PRIMÄR UND SEKUNDÄRQUELLEN
PRIMÄRQUELLEN
QUELLENVERZEICHNIS
QUELLVERZEICHNIS
QUELLEN
REFERENCE
REFERENCES
SAMMELWERKE
SEKUNDÄRQUELLEN
VIDEOQUELLEN
WEBLIOGRAPHIE
WEITERFÜHRENDE LITERATUR
ZEITSCHRIFTENARTIKEL
""")

CHAPTER = utila.splitlines("""
AUFBAU
AUFBAU UND GLIEDERUNG
AUSBLICK
CONCLUSIO
CONCLUSION
CONCLUSIONS
DATENAUSWERTUNG
DISCUSSION
DISKUSSION
DISKUSSION UND AUSBLICK
EINFÜHRUNG
EINLEITUNG
EINLEITUNG UND MOTIVATION
EINLEITUNG UND ZIELSETZUNG
ERGEBNIS
ERGEBNISSE
FORSCHUNGSFRAGE
FORSCHUNGSFRAGEN UND HYPOTHESEN
FORSCHUNGSPLAN
FORSCHUNGSSTAND
FRAGESTELLUNG UND HERANGEHENSWEISE
GRUNDLAGEN
INTRODUCTION
KONKLUSION
KONZEPTION
MATERIAL UND METHODEN
MATERIAL, METHODIK UND QUELLENLAGE
MOTIVATION UND ZIELSETZUNG
PERSPEKTIVEN
RESÜMEE
SCHLUSS
SCHLUSSBEMERKUNGEN
SCHLUSSBETRACHTUNG
STAND DES WISSENS
THEORETISCHER HINTERGRUND
ZIELE, AUFBAU UND METHODE
ZIELSETZUNG UND AUFBAU DER ARBEIT
ZUSAMMENFASSUNG & AUSBLICK
ZUSAMMENFASSUNG UND AUSBLICK
""")

FIGURETABLE = utila.splitlines("""
ABBILDUNGEN
ABBILDUNGSVERZEICHNIS
LIST OF FIGURES
""")

GLOSSARY = utila.splitlines("""
GLOSSAR
GLOSSAR / KLÄRUNG RELEVANTER BEGRIFFE
GLOSSARY
STICHWORTVERZEICHNIS
""")

LEGAL = utila.splitlines("""
EHRENWÖRTLICHE ERKLÄRUNG
EIDESSTATTLICHE ERKLÄRUNG
EIDESSTATTLICHE VERSICHERUNG
ERKLÄRUNG
VERSICHERUNG AN EIDES STATT
VERSICHERUNG SELBSTÄNDIGER ARBEIT
""")

SYMBOLTABLE = utila.splitlines("""
ABKÜRZUNG UND NOMENKLATUR
ABKÜRZUNGSVERZEICHNIS
NOMENKLATUR
SYMBOL
SYMBOLE
SYMBOLS
SYMBOLVERZEICHNIS
VERZEICHNIS DER VERWENDETEN ABKÜRZUNGEN
""")

TABLETABLE = utila.splitlines("""
LIST OF TABLES
TABELLEN
TABELLENVERZEICHNIS
""")

TOC = utila.splitlines("""
CONTENTS
CONTENT
GLIEDERUNG
INHALTSVERZEICHNIS
INHALT
TABLE OF CONTENTS
TABLE OF CONTENT
""")

UTILS = utila.splitlines("""
PUBLICATIONS
FORMELVERZEICHNIS
VORWORT
""")

VITAE = utila.splitlines("""
CURRICULUM VITAE
LEBENSLAUF
""")

LISTINGS = utila.splitlines("""
LISTING
LISTINGS
VERZEICHNIS DER LISTINGS
""")

HEADLINES = (ABBREVIATION | ABSTRACT | ACKNOWLEDGE | APPENDIX | BIBLIOGRAPHY |
             CHAPTER | FIGURETABLE | GLOSSARY | LEGAL | SYMBOLTABLE |
             TABLETABLE | TOC | UTILS | VITAE | LISTINGS)
