# =============================================================================
# C O P Y R I G H T
# -----------------------------------------------------------------------------
# Copyright (c) 2021-2022 by Helmut Konrad Fahrendholz. All rights reserved.
# This file is property of Helmut Konrad Fahrendholz. Any unauthorized copy,
# use or distribution is an offensive act against international law and may
# be prosecuted under federal law. Its content is company confidential.
# =============================================================================

import utila

ABBREVIATION = utila.splitlines("""
ABBREVIATION
ABBREVIATIONS
ABBREVIATIONTABLE
ABKÜRZUNGEN
ABKÜRZUNGEN UND SYMBOLE
ABKÜRZUNGSVERZEICHNIS
ACRONYME
ACRONYMS
""")

ABSTRACT = utila.splitlines("""
ABSTRACT
ABSTRACT IN ENGLISH
ABSTRACT OF THE DISSERTATION
ABSTRACT OF THE THESIS
ABSTRAKT AUF DEUTSCH
AN ABSTRACT OF THE THESIS OF
KURZFASSUNG
KURZZUSAMMENFASSUNG
ZUSAMMENFASSUNG
""")

ACKNOWLEDGE = utila.splitlines("""
ACKNOWLEDGE
ACKNOWLEDGEMENT
ACKNOWLEDGEMENTS
ACKNOWLEDGMENT
ACKNOWLEDGMENTS
DANKSAGUNG
DANKSAGUNGEN/WIDMUNGEN
DEDICATION
""")

APPENDIX = utila.splitlines("""
A. ANHANG
B. ANHANG
C. ANHANG
D. ANHANG
ANHANG 1
ANHANG 2
ANHANG 3
ANHANG 4
ANHANG 5
ANHANG 6
ANHANG 7
ANHANG 8
ANHANG 9
ANHANG 10
ANHANG A
ANHANG B
ANHANG C
ANHANG D
ANHANG
ANHANGSVERZEICHNIS
APPENDIX
I ANHANG
II ANHANG
III ANHANG
IIII ANHANG
IV ANHANG
V ANHANG
VI ANHANG
VII ANHANG
VIII ANHANG
""")

BIBLIOGRAPHY = utila.splitlines("""
INTERNETQUELLEN
BIBLIOGRAFIE
BIBLIOGRAPHIE
BIBLIOGRAPHY
LITERATUR
LITERATUR UND QUELLENVERZEICHNIS
LITERATUR- UND QUELLENVERZEICHNIS
LITERATURANGABEN
LITERATURLISTE
LITERATURE
LITERATURVERZEICHNIS
QUELLEN
QUELLENVERZEICHNIS
REFERENCE
REFERENCES
WEITERFÜHRENDE LITERATUR
ZEITSCHRIFTENARTIKEL
""")

CHAPTER = utila.splitlines("""
AUFBAU
AUFBAU UND GLIEDERUNG
AUSBLICK
CONCLUSIO
CONCLUSION
DISCUSSION
DISKUSSION
DISKUSSION UND AUSBLICK
EINFÜHRUNG
EINLEITUNG
EINLEITUNG UND MOTIVATION
EINLEITUNG UND ZIELSETZUNG
ERGEBNIS
ERGEBNISSE
FORSCHUNGSFRAGE
GRUNDLAGEN
INTRODUCTION
MATERIAL UND METHODEN
MOTIVATION UND ZIELSETZUNG
PERSPEKTIVEN
RESÜMEE
SCHLUSSBETRACHTUNG
STAND DES WISSENS
ZIELE, AUFBAU UND METHODE
ZIELSETZUNG UND AUFBAU DER ARBEIT
ZUSAMMENFASSUNG & AUSBLICK
ZUSAMMENFASSUNG UND AUSBLICK
""")

FIGURETABLE = utila.splitlines("""
ABBILDUNGEN
ABBILDUNGSVERZEICHNIS
LIST OF FIGURES
""")

GLOSSAR = utila.splitlines("""
GLOSSAR
GLOSSAR / KLÄRUNG RELEVANTER BEGRIFFE
GLOSSARY
STICHWORTVERZEICHNIS
""")

LEGAL = utila.splitlines("""
ERKLÄRUNG
EIDESSTATTLICHE ERKLÄRUNG
EIDESSTATTLICHE VERSICHERUNG
""")

SYMBOLTABLE = utila.splitlines("""
ABKÜRZUNGSVERZEICHNIS
ABKÜRZUNG UND NOMENKLATUR
SYMBOL
SYMBOLE
SYMBOLS
SYMBOLVERZEICHNIS
""")

TABLETABLE = utila.splitlines("""
LIST OF TABLES
TABELLEN
TABELLENVERZEICHNIS
""")

TOC = utila.splitlines("""
CONTENT
CONTENTS
INHALT
INHALTSVERZEICHNIS
TABLE OF CONTENT
TABLE OF CONTENTS
""")

UTILS = utila.splitlines("""
PUBLICATIONS
FORMELVERZEICHNIS
VORWORT
""")

VITAE = utila.splitlines("""
CURRICULUM VITAE
LEBENSLAUF
""")

LISTINGS = utila.splitlines("""
LISTING
LISTINGS
VERZEICHNIS DER LISTINGS
""")

HEADLINES = (ABBREVIATION | ABSTRACT | ACKNOWLEDGE | APPENDIX | BIBLIOGRAPHY |
             CHAPTER | FIGURETABLE | GLOSSAR | LEGAL | SYMBOLTABLE |
             TABLETABLE | TOC | UTILS | VITAE | LISTINGS)
